services:

  app_v1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app_v1
    command: uvicorn --factory src.presentation.api.v1.main:create_app --host 0.0.0.0 --port 8055
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8055:8055"

  app_v2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app_v2
    command: uvicorn --factory src.presentation.api.v2.main:create_app --host 0.0.0.0 --port 8050
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8050:8050"